// app/layout.tsx


import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// Removed Header and Toaster from here, they are now in layout-client.tsx

// Import Inter Display font
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Import the client wrapper component
import LayoutClientWrapper from "./layout-client"; // Adjust path if needed

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Keep inter.variable here as it's a CSS variable, can be applied server-side */}
      <body className={`${inter.variable} antialiased`}>
        {/* Use the client wrapper component */}
        <LayoutClientWrapper>
          {children}
        </LayoutClientWrapper>
      </body>
    </html>
  );
}